---
#####################
# sample HTPasswd CR
#####################
# https://docs.openshift.com/container-platform/4.1/authentication/identity_providers/configuring-htpasswd-identity-provider.html
# 
# https://docs.ansible.com/ansible/latest/modules/htpasswd_module.html?highlight=apache%20htpasswd
# 
# https://github.com/jkupferer/ansible-role-openshift_htpasswd_oauth
# install the role first:
#
# ansible-galaxy install https://github.com/jkupferer/ansible-role-openshift_htpasswd_oauth/archive/master.tar.gz#/openshift_htpasswd_oauth
# 
######################

- name: configure htpasswd auth for OCP
  hosts: localhost
  gather_facts: false
  roles: 
  - openshift_htpasswd_oath
  vars:
    openshift_htpasswd_users:
    - name: alice
      password: p4ssw0rd
    - name: bob
      password: p4ssw0rd
    openshift_htpasswd_remove_users: true


  
