---
- name: configure htpasswd auth for OCP

#####################
# sample HTPasswd CR
#####################
# https://docs.openshift.com/container-platform/4.1/authentication/identity_providers/configuring-htpasswd-identity-provider.html
# 
# https://docs.ansible.com/ansible/latest/modules/htpasswd_module.html?highlight=apache%20htpasswd
# 
# 
# 
#  apiVersion: config.openshift.io/v1
#  kind: OAuth
#  metadata:
#    name: cluster
#  spec:
#    identityProviders:
#    - name: my_htpasswd_provider 
#      mappingMethod: claim 
#      type: HTPasswd
#      htpasswd:
#        fileData:
#          name: htpass-secret
#  
######################

  
